name: CI/CD workflow

on: 
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    name: Build npm package
    if: "!startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish npm package to Github
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/publish.yml

