name: CI/CD workflow

on: 
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build npm package
        uses: ./.github/actions/build

      - name: Publish npm package
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/publish

