name: CI/CD Workflow

on: 
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']

permissions:
  checks: write
  contents: write
  packages: write
  id-token: write
  pull-requests: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get NodeJS version
        shell: bash
        run: |
          NODEJS_VERSION=$(jq -r '.packages[] | select(startswith("nodejs@")) | split("@")[1]' devbox.json)
          echo "NODEJS_VERSION=$NODEJS_VERSION" >> $GITHUB_ENV
              
      - name: Get PNPM version
        shell: bash
        run: |
          PNPM_VERSION=$(jq -r '.packageManager | split("@")[1]' package.json)
          echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_ENV
        
      - name: Build npm package
        uses: ./.github/actions/build
        with:
          nodejs-version: ${{ env.NODEJS_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

      - name: Publish npm package
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/publish
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          npm-token: ${{ secrets.NPM_WRITE_PACKAGES_TOKEN }}

