name: Publish package to GitHub Packages

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@FMI-MediaMaster'

      - name: Install pnpm 
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Set Tag Name
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          TAG_VERSION=${TAG_NAME#/v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Set package version
        run: pnpm version ${{ env.TAG_VERSION }} --no-git-tag-version

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
